const CREATE_USER = 'CREATE_USER';
const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export {
  CREATE_USER, CREATE_USER_SUCCESS, CREATE_USER_ERROR,
};
